# Generated by Django 4.1.13 on 2024-09-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='account_id',
            field=models.CharField(default='id not provided', editable=False, max_length=40),
        ),
    ]
