# Generated by Django 4.1.13 on 2024-10-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, max_length=100, verbose_name='priority'),
        ),
    ]
