# Generated by Django 4.1.13 on 2024-10-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='projection_id',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
