# Generated by Django 4.1.13 on 2024-10-23 03:35

import check_products.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCheck',
            fields=[
                ('id', models.CharField(default=check_products.models.generate_check_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255)),
                ('activities', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'product_check',
            },
        ),
    ]
