# Generated by Django 4.1.13 on 2024-10-29 05:41

import check_products.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCheck',
            fields=[
                ('id', models.CharField(default=check_products.models.generate_check_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255, unique=True)),
                ('categories', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Product Check',
                'verbose_name_plural': 'Product Checks',
                'db_table': 'product_check',
            },
        ),
    ]
