# Generated by Django 4.1.13 on 2024-10-23 03:50

import check_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcheck',
            options={'verbose_name': 'Product Check', 'verbose_name_plural': 'Product Checks'},
        ),
        migrations.AlterField(
            model_name='productcheck',
            name='account_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productcheck',
            name='id',
            field=models.CharField(default=check_products.models.generate_check_id, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
