# Generated by Django 4.1.13 on 2024-11-17 02:04

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=documents.models.generate_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('projection_id', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.BinaryField()),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'documents',
            },
        ),
    ]
