# Generated by Django 4.1.13 on 2024-11-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_Projection_Dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultprojectiondates',
            options={'verbose_name': 'Fecha de proyección por defecto', 'verbose_name_plural': 'Fechas de proyección por defecto'},
        ),
    ]
