# Generated by Django 4.1.13 on 2024-10-22 05:28

import conditions_categories.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_academica', djongo.models.fields.EmbeddedField(model_container=conditions_categories.models.CargaAcademica)),
                ('otras_actividades', djongo.models.fields.EmbeddedField(model_container=conditions_categories.models.ActividadSimple)),
                ('investigacion', djongo.models.fields.EmbeddedField(model_container=conditions_categories.models.ActividadSimple)),
                ('superacion_academica', djongo.models.fields.EmbeddedField(model_container=conditions_categories.models.ActividadSimple)),
                ('actividades_complementarias', djongo.models.fields.EmbeddedField(model_container=conditions_categories.models.ActividadSimple)),
                ('actividades_extension', djongo.models.fields.EmbeddedField(model_container=conditions_categories.models.ActividadSimple)),
            ],
        ),
    ]
