# Generated by Django 4.1.13 on 2024-10-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'condition_category', 'verbose_name_plural': 'conditions_categories'},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='conditions_categories',
        ),
    ]
