# Generated by Django 4.1.13 on 2024-10-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='units',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
