# Generated by Django 4.1.13 on 2024-10-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='projection',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
