# Generated by Django 4.1.13 on 2024-10-05 01:48

from django.db import migrations, models
import projections.models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0002_projection_color_projection_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='color',
            field=models.CharField(blank=True, default=projections.models.generate_pastel_color, max_length=7),
        ),
    ]
