# Generated by Django 4.1.13 on 2024-10-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0002_projection_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='priority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
