# Generated by Django 5.1 on 2024-08-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_TT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Users_TT',
        ),
    ]
