# Generated by Django 5.1 on 2024-08-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_TT', '0002_rename_users_users_tt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_TT',
        ),
    ]
