# Generated by Django 4.1.13 on 2024-11-17 20:34

from django.db import migrations, models
import documents_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_admin', '0002_alter_documentsadmin_file_alter_documentsadmin_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsadmin',
            name='file',
            field=models.FileField(upload_to='', validators=[documents_admin.models.validate_file_extension], verbose_name='Archivo'),
        ),
    ]
