# Generated by Django 4.1.13 on 2024-11-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents_admin', '0003_alter_documentsadmin_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsadmin',
            options={'verbose_name': 'Documento oficial', 'verbose_name_plural': 'Documentos oficiales'},
        ),
    ]
