# Generated by Django 4.1.13 on 2024-08-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={},
        ),
        migrations.AlterModelTable(
            name='teachers',
            table='teachers',
        ),
    ]
