# Generated by Django 4.1.13 on 2024-09-02 03:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default=accounts.models.generateIdTask, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
