# Generated by Django 4.1.13 on 2024-08-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accounts',
            table='accounts',
        ),
    ]
