# Generated by Django 4.1.13 on 2024-10-10 18:11

from django.db import migrations, models
import djongo.models.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(default=products.models.generate_product_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255)),
                ('projection_id', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('tasks', djongo.models.fields.JSONField(blank=True, null=True, verbose_name=models.CharField(max_length=255))),
                ('documents_required', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('units', models.FloatField(blank=True, default=0, null=True)),
                ('priority', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default=products.models.generate_pastel_color, max_length=7)),
                ('progress', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
    ]
