# Generated by Django 4.1.13 on 2024-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='projection_id',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
