# Generated by Django 4.1.13 on 2024-10-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='units_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
