# Generated by Django 4.1.13 on 2024-10-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_units_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='documents_number',
            field=models.IntegerField(default=0),
        ),
    ]
