# Generated by Django 4.1.13 on 2024-09-30 01:09

import calendar_dates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Event',
            fields=[
                ('id', models.CharField(default=calendar_dates.models.generate_date_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'date',
                'verbose_name_plural': 'dates',
                'db_table': 'dates',
            },
        ),
        migrations.AddIndex(
            model_name='date_event',
            index=models.Index(fields=['start_date', 'end_date'], name='dates_start_d_8a055d_idx'),
        ),
    ]
